//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCoolNew2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static SportCoolNew2.Models.MetaData;

    [MetadataType(typeof(MataActivity))]

    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.HoldList = new HashSet<HoldList>();
        }
    
        public int activityId { get; set; }
        public string name { get; set; }
        public string place { get; set; }
        public System.DateTime dateTime { get; set; }
        public string item { get; set; }
        public string holder { get; set; }
        public string activitycontent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoldList> HoldList { get; set; }
    }
}
