//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCoolNew2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static SportCoolNew2.Models.MetaData;
    [MetadataType(typeof(MetadataMember))]
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Coach = new HashSet<Coach>();
            this.DietRecord = new HashSet<DietRecord>();
            this.Evaluation = new HashSet<Evaluation>();
            this.Friend = new HashSet<Friend>();
            this.HoldList = new HashSet<HoldList>();
            this.MComment = new HashSet<MComment>();
            this.MemberSelectClass = new HashSet<MemberSelectClass>();
            this.MRead = new HashSet<MRead>();
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Shop = new HashSet<Shop>();
            this.Gift = new HashSet<Gift>();
            this.Category = new HashSet<Category>();
            this.Commodity = new HashSet<Commodity>();
            this.Keyword = new HashSet<Keyword>();
        }
    
        public int mId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string identityId { get; set; }
        public string name { get; set; }
        public bool gender { get; set; }
        public string Checkpassword { get; set; }
        public System.DateTime birthday { get; set; }
        public Nullable<int> age { get; set; }
        public string phone { get; set; }
        public string postalCode { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string other { get; set; }
        public int mTypeId { get; set; }
        public int wayofdietId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public bool emailstatus { get; set; }
        public Nullable<int> bvId { get; set; }
        public Nullable<int> aLId { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> BMI { get; set; }
        public Nullable<double> BMR { get; set; }
        public Nullable<double> TDEE { get; set; }
        public decimal credits { get; set; }
        public string photoSticker { get; set; }
    
        public virtual Activity_Level Activity_Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coach> Coach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DietRecord> DietRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoldList> HoldList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MComment> MComment { get; set; }
        public virtual MemberType MemberType { get; set; }
        public virtual WayOfDiet WayOfDiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberSelectClass> MemberSelectClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MRead> MRead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gift> Gift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commodity> Commodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Keyword> Keyword { get; set; }
    }
}
