//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCoolNew2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportCoolEntities : DbContext
    {
        public SportCoolEntities()
            : base("name=SportCoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Activity_Level> Activity_Level { get; set; }
        public virtual DbSet<Anc> Anc { get; set; }
        public virtual DbSet<Blacklist> Blacklist { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryManager> CategoryManager { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<ClassGrade> ClassGrade { get; set; }
        public virtual DbSet<ClassType> ClassType { get; set; }
        public virtual DbSet<Coach> Coach { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<CommentManager> CommentManager { get; set; }
        public virtual DbSet<Commodity> Commodity { get; set; }
        public virtual DbSet<CommodityManager> CommodityManager { get; set; }
        public virtual DbSet<Diet> Diet { get; set; }
        public virtual DbSet<DietRecord> DietRecord { get; set; }
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<Gift> Gift { get; set; }
        public virtual DbSet<GiftManager> GiftManager { get; set; }
        public virtual DbSet<HoldList> HoldList { get; set; }
        public virtual DbSet<Keyword> Keyword { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<MComment> MComment { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberSelectClass> MemberSelectClass { get; set; }
        public virtual DbSet<MemberType> MemberType { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<MRead> MRead { get; set; }
        public virtual DbSet<Nutrient> Nutrient { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<QA> QA { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TrendingArticles> TrendingArticles { get; set; }
        public virtual DbSet<TrendingManager> TrendingManager { get; set; }
        public virtual DbSet<WayOfDiet> WayOfDiet { get; set; }
    }
}
