//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCoolNew2.Models
{
    using System;
    using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;
    using static SportCoolNew2.Models.MetaData;

    [MetadataType(typeof(MetaTrendingArticles))]
    public partial class TrendingArticles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrendingArticles()
        {
            this.MRead = new HashSet<MRead>();
            this.TrendingManager = new HashSet<TrendingManager>();
        }
    
        public int articlesId { get; set; }
        public string aContent { get; set; }
        public string article { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MRead> MRead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrendingManager> TrendingManager { get; set; }
    }
}
